### ISSUE TITLE
DPL-1077 - As a long read user I want to see an automatic volume check when I add a library to a sequencing run to ensure the integrity of the data is maintained

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#1518]
**User story**
As a long read user I want to see an automatic volume check when I add a library to a sequencing run to ensure the integrity of the data is maintained

**Who are the primary contacts for this story**
Ben / Steve / James / Seena

**Who is the nominated tester for UAT**
James / Long Read

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] the ability to add the volume required when I add a library to a well in a sequencing run
- [ ] an automated check to ensure that there is enough library available
- [ ] an appropriate message if there is not enough
- [ ] a success message if the volume is accepted and the library is added

RunCreate store structure
- Currently in PacBio Run Create store we send a list of pool_ids and library_ids in each well that then creates the used_aliquots in the service. We should update this so we send a list of used_aliquots instead (with their new volumes) and change the API to remove pool_ids and library_ids. See https://github.com/sanger/traction-service/pull/1274#discussion_r1559041462 for more information

**Dependencies**
This story is blocked by the following dependencies:
- sanger/traction-service#1186
- sanger/traction-service#1136

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**
- Volume checking process map: [https://lucid.app/lucidchart/3c12fbb3-5265-49b5-9f6a-97c9a69a59eb/edit?viewport_l[…]3271%2C0_0&invitationId=inv_4a6b1f8d-e886-4ffc-b784-40f2135c0679](https://lucid.app/lucidchart/3c12fbb3-5265-49b5-9f6a-97c9a69a59eb/edit?viewport_loc=116%2C-4472%2C6583%2C3271%2C0_0&invitationId=inv_4a6b1f8d-e886-4ffc-b784-40f2135c0679)
- Multiplexing ERD: https://lucid.app/lucidchart/56eec268-2911-44c4-ab4b-87393e811738/edit?view_items=Fm2l5AbOONXb&invitationId=inv_81ba033e-8594-44c3-a37f-fd0c07fb4803
- Multiplexing process map: https://lucid.app/lucidchart/343de76c-d3e5-4a26-92c4-7bc10d919fb8/edit?page=0_0&invitationId=inv_13a8dd3b-ef1b-4f4e-b160-0dbf45a6031f#
