### ISSUE TITLE
Y24-141 - As a team lead (Danni) I would like to have a reception so that I can scan tubes and plates into locations without having to visit labwhere and to speed up the process

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#1773]
**User story**
As a team lead (Danni) I would like to have reception so that I can scan tubes and plates into locations without having to visit labwhere and to speed up the process

**Who are the primary contacts for this story**
Steve / Danni / James

**Who is the nominated tester for UAT**
Steve / Danni / James

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] A location reception page in traction
- [x] An input for the User swipe card id / barcode
- [x] An input for the location barcode
- [x] An input for the start position
- [x] An input for the barcodes
- [x] A counter for how many barcodes are to be scanned
- [x] A big button to submit the scan
- [x] Feedback if the scan fails
- [x] Feedback if the scan succeeds
- [x] The locations to be updated in labwhere
- [x] Validation for duplicate barcodes

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #714

**Additional context**
