### ISSUE TITLE
Y24-143 - As developers we need to create a software library for managing locations from labwhere that we can use in traction so that long read user can see where their samples are without having to go to labwhere

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#1774]
**User story**
As developers we need to create a library locations from labwhere so that we can use in traction so that long read user can see where their samples are without having to go to labwhere

**Who are the primary contacts for this story**
Steve / Danni / James

**Who is the nominated tester for UAT**
Steve / Danni / James

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] A new method of data retrieval as labwhere does not use JSON API
- [ ] A separate library which can be reused in multiple views
- [ ] Fetch locations from labwhere for multiple barcodes
- [ ] Retrieval of the co-ordinate for a barcode as they are working in boxes

**Dependencies**
This story is blocked by the following dependencies:
- #714 

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**
