### ISSUE TITLE
Y24-145 - As a team lead (Danni) I would like to see the location for samples so that I know where my stuff is and I can find it easier without having to visit labwhere and speed up the process

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#1776]
**User story**
As a team lead (Danni) I would like to see the location for samples so that I know where my stuff is and I can find it easier without having to visit labwhere and speed up the process

**Who are the primary contacts for this story**
Steve / Danni / James

**Who is the nominated tester for UAT**
Steve / Danni / James

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] When I visit the ONT samples page I should see the location and co-ordinate for each sample
- [x] When I visit the Pacbio samples page I should see the location and co-ordinate for each sample
- [x] The locations should load asynchronously and page load should not fail if labwhere is not available.

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
-  #714

**Additional context**
