### ISSUE TITLE
Y24-149 - As a team lead (Danni) I would like to be able to exhaust samples when I move them to a destroyed location in the location reception so that I do not have to do any extra work by setting the volume to zero which is useful for volume tracking and reporting

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#1780]
**User story**
As a team lead (Danni) I would like to be able to exhaust samples when I move them to a destroyed location in the location reception so that I do not have to do any extra work by setting the volume to zero which is useful for volume tracking and reporting

**Who are the primary contacts for this story**
Steve / Danni / James

**Who is the nominated tester for UAT**
Steve / Danni / James

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] I should be able to visit the location reception page and scan a sample into destroyed
- [ ] If the sample exists in traction it should exhaust the sample (set the volume to zero)
- [ ] A message should be sent to the warehouse to set the volume to zero for the aliquot

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #714

**Additional context**
