### ISSUE TITLE
DPL-251 Improve automatic sample sheet generation by tracking Adaptive Loading and Loading Target (P1+ P2) [M]

### ISSUE THREAD

**Issue by JamesGlover** [sanger/traction-ui#701]
**User story**

As a traction user, I would like to track new fields to assist with sample sheet generation.

> Sequencing of Microbial, HiFi and ULI libraries. If binding kit v2.2 is used we need to be able to specify Adaptive Loading/ Loading Target ‘Loading Target (P1 + P2)’ in run design, per well (Default set to: 0.85). I mentioned to Ben a while ago in an email when we were initially looking at the incompatibility with the latest version of SMRTLink. There is now a new option available as part of the run design/ csv setup (I think has been available since SMRTLink  10.0), We can now set ‘Application’. With our current csv file output this defaults to ‘custom’. However, we could for IsoSeq samples or any sample once we have appropriate flags in place, set the application to ‘IsoSeq Method’ or appropriate other application. I was hoping that this would automatically set the correct default values for other aspect for the run design but on further testing this does not appear to be the case. I have now played around with the traction generated sample sheet csv and currently SMRTLink detects that v2.2 binding kit is being used so automatically sets ‘Use Adaptive Loading’ to YES and ‘Loading Target (P1+ P2) to 0.75 but I think we need to be able to control these settings within TRACTION. These will require additional options to be present when we set up the run per well. Once we have library flags in place it would be good to define specific defaults for each library type to minimise run setup errors.

**Who are the primary contacts for this story**
Craig C
James W

**Acceptance criteria (MVP)**
To be considered successful the solution must allow:
- [ ] Add optional `Loading Target (P1+ P2)` to each well at run creation
- [ ] This should be passed along to the traction-service with the pacbio/runs/well creation (See https://github.com/sanger/traction-service/issues/731)
- [ ] User should see clear feedback about the status of 'Use adaptive loading'

**Acceptance criteria (Related stories)**

These are other requirements that came out of the discussion that can be delivered as separate stories.

- [ ] #732 
- [ ] #733

**Dependencies**
We will have a matching story in traction service to update the sample sheet and store the returned data. There may also be a need to adapt where library type options 'live'.

https://github.com/sanger/traction-service/issues/701

**Additional context**

Currently library types for a given pipeline are stored in the front-end, however we may wish to move this to traction-service to allow these options to be updated without redeployment.

**Comment by stevieing** [comment]
More information is required before we can proceed.

**Comment by JamesGlover** [comment]
Hello all,
 
I was wondering if you had a chance to discuss this, we have two draft stories in place with possible requirements:
 
https://github.com/sanger/traction-ui/issues/701
https://github.com/sanger/traction-service/issues/701
 
In terms of the user-facing changes, this translates as:
 
- Add `Application` column  to sample sheet populated based on library type. (Can this just be filled with the library type?)
- Add `Use Adaptive Loading` and `Loading Target (P1+ P2)` to CSV
- Add default options for the above options for each library type
- Add `Use Adaptive Loading` and `Loading Target (P1+ P2)` to each well at run creation Populate with defaults based on library type
populate based on binding kit used and pre-extension value (if possible, see below in Q section)
- Keep track of the options filled in above in the database
 
Questions:
 
- Does the above sound accurate?
Yes, except where commented.
- Are the column titles exactly as they appear between the backticks
`Application` - Correct
`Use Adaptive Loading` - correct
`Loading Target (P1+ P2)` - typo should be `Loading Target (P1 + P2)`
 
- Can we populate `Application` with the library type, if not, can we have the values that will be needed?
No (not any more).
Based on the current library types we have present in traction the application relationship is as follows:
Pacbio_HiFi --> `HiFi Reads`
Pacbio_HiFi_mplx --> `HiFi Reads`
Pacbio_Microbial_mplx --> `Microbial Assembly`
Pacbio_IsoSeq --> `Iso-Seq Method`
PacBio_IsoSeq_mplx --> `Iso-Seq Method`
PacBio_Ultra_Low_Input --> `HiFi Reads`
PacBio_Ultra_Low_Input_mplx --> `HiFi Reads`
 
- What values are appropriate for each column? Are they required?
`Use Adaptive Loading` (TRUE/ FALSE) depends on the binding kit used, if “Binding Kit Box Barcode” string contains the following product IDs `101820500` or ` 101789500` then FALSE, if contains `101894200’ then TRUE
 
For simplicity only `Iso-Seq Method` cannot use Adaptive loading, so `Use Adaptive Loading` should be FALSE and `Loading Target (P1 + P2)` blank with Iso-seq library types, all other library types are using adaptive loading. However, if you can base on the binding kit barcode that would be better and possibly more future proof especially for when kits are retired and new ones introduced. Following this route, it would be good to move the “Binding kit barcode” field on the “Add Pool to Well:” screen to the top so if we need to change the default kit from the first screen it can be scanned straight away and any defaults based on the binding kit are updated accordingly.
 
The way we are operating at the moment with the `Loading Target (P1 + P2)`, when setting the well up on run design:
if Pre-extension time (hours) = 0 : `Loading Target (P1 + P2)` = 0.75
if Pre-extension time (hours) = 2 : `Loading Target (P1 + P2)` = 0.85
 
- What are the defaults for each library type?
Complicated at the moment due to different ‘sub-library types’ possible in “Pacbio_HiFi”, this should change very soon as there should only be 1x Library prep type for all Hifi libraries with a kit change due to be released this quarter.
If we can have the default changing as directly above relating to pre-extension time (but with the option to manually over-ride) that should suffice.
